### ISSUE TITLE
Documentación o ejemplo para complemento pagos 2.0

### ISSUE THREAD

**Issue by corzahk** [eclipxe13/CfdiUtils#100]
Hola buenas comunidad, he estado indagando e implementado la librería de cfdi, pero tengo una duda se que existe el modulo de recepción de pagos pero no encuentro la documentación para poder aplicarlo alguien tendrá el link o ejemplo que me pudiera proporcionar por favor.

**Comment by TheSpectroMx** [comment]
Hola @corzahk puedes echarle un ojo al siguiente issue https://github.com/eclipxe13/CfdiUtils/issues/98 revisalo y espero te funcione si no esperamos tus comentarios.

**Comment by corzahk** [comment]
muchas gracias me ha funcionado

**Comment by TheSpectroMx** [comment]
Perfecto @corzahk te invito a cerrar el issue y en su caso si gustas entrar a la comunidad de discord para una comunicación más rápida, el link es https://discord.gg/thBF87fA
