### ISSUE TITLE
Documentación Pagos20

### ISSUE THREAD

**Issue by kunkanon** [eclipxe13/CfdiUtils#103]
¿Hay alguna documentación para usar la clase Pagos20 para Pago Parcialidades?
Algo como RetencionesCreator20 pero para los pagos20 y para pago parcialidades?

Ejemplo de xml:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/23107622/181635931-a83f7bbe-4ea8-4b6f-8494-ec06fd876180.png">

Saludos,

**Comment by eclipxe13** [comment]
No hay documentación específica, solo genérica de `Elements` en https://cfdiutils.readthedocs.io/es/latest/componentes/elements.html#estructura-de-datos-elements

El elemento de ayuda es la clase `CfdiUtils\Elements\Pagos20\Pagos`.

También puedes ver el código de https://github.com/eclipxe13/CfdiUtils/blob/master/tests/CfdiUtilsTests/CreateComprobantePagos33CaseTest.php donde se está creando un CFDI 3.3 y Pagos 1.0 usando el elemento de ayuda `CfdiUtils\Elements\Pagos10\Pagos`. El código para CFDI 4.0 y Pagos 2.0 es parecido.

**Comment by kunkanon** [comment]
Perfecto.
Muchas gracias.
