### ISSUE TITLE
Call to undefined method CfdiUtils\Elements\Cfdi33\Traslado::addRetencion()

### ISSUE THREAD

**Issue by GenaroDominguez96** [eclipxe13/CfdiUtils#105]
Alguna forma de solucionar este error Call to undefined method CfdiUtils\Elements\Cfdi33\Traslado::addRetencion()
$comprobante->addConcepto([
            'ClaveProdServ' => '50211503',
            'NoIdentificacion' => 'NoId',
            'Cantidad' => '1',
            'ClaveUnidad' => 'H87',
            'Unidad' => 'Pieza',
            'Descripcion' => 'Producto Generico',
            'ValorUnitario' => '100.00',
            'Importe' => '100.00',
            'Descuento' => '0',
            'ObjetoImp' => '02',
        ])->addTraslado([
            'Base'=>'1.00',
            'Impuesto'=>'002',
            'TipoFactor'=>'Tasa',
            'TasaOCuota'=>'0.160000',
            'Importe'=>'16.00',           
        ])->addRetencion([
            'Base'=>'1.00',
            'Impuesto'=>'001',
            'TipoFactor'=>'Tasa',
            'TasaOCuota'=>'0.100000',
            'Importe'=>'0.00',
        ]);

**Comment by TheSpectroMx** [comment]
Hola @GenaroDominguez96 ahí lo que estas haciendo es agregar el Retenido al Traslado del concepto. Puedes intentar haciendo:
```php
$concepto = $comprobante->addConcepto([
@atributos
]);

$concepto->addTraslado([
@atributos
]);

$concepto->addRetencion([
@atributos
]);```

**Comment by GenaroDominguez96** [comment]
Justo, gracias
