### ISSUE TITLE
Call to undefined method cfdi::getQuickReader

### ISSUE THREAD

**Issue by juancarlosso** [eclipxe13/CfdiUtils#106]
Buen dia muchachos.
Estoy obteniendo este error pero solo en el servidor, en el desarrollo local funciona sin problemas.
Uso Laravel en mi desarrollo.
[Screenshot](https://share.cleanshot.com/XH3tfb)

Gracias

**Comment by eclipxe13** [comment]
Me temo que no estás usando la última versión de la librería.
¿Qué versiones estás usando en tu definición de dependencias?
¿Qué versión está instalada en desarrollo y en producción?

Creo que es más fácil ayudarte en el canal de discord de la comunidad: https://discord.gg/aFGYXvX

**Comment by eclipxe13** [comment]
El problema era que se estaba usando una versión antigua 2.2.0 y *QuickReader* fue agregado en 2.6.0.
