### ISSUE TITLE
CartaPorte V 3.0 

### ISSUE THREAD

**Issue by superalgoritmo** [eclipxe13/CfdiUtils#114]
No se si esten teniendo problemas con el xml de cpp 3.0 ya que en 2.0 me hace el sello bien pero en 3.0 
 El resultado de la digestión debe ser igual al resultado de la desencripción del sello. Cadena Origial:||4.0|TEST|414|2023-11-21T13:13:47|99|30001000000500003364|5500.50|MXN|1|6380.58|I|01|PPD|44960|XIQB891116QE4|BERENICE XIMO QUEZADA|626|FUNK671228PH6|KARLA FUENTE NOLASCO|44970|612|G03|78121603|1002|1.00|E48|Servicio de Flete Nacional|5500.50|5500.50|02|5500.50|002|Tasa|0.160000|880.08|5500.50|002|Tasa|0.160000|880.08|880.08|3.0|CCCBCD94-870A-4332-A52A-A52AA52AA52A|No|213|No|01|01|Origen|OR000001|EKU9003173C9|GRUPO INDUSTRIAL DELEBA SA DE CV|2024-09-11T00:00:00|Paseo del Estribillo|213213|1457|09|Puerta cafe|042|SON|MEX|85800|Destino|DE000001|EKU9003173C9|NombreRemitenteDestinatario1|2024-09-11T18:00:00|213|Privada de la Soledad|12312|2755|07|Puerta cafe|030|SON|MEX|83198|100|KGM|1000|1|1500.00|No|10101504|543215|tester|1|KGM|PAR|18/62/31cm|Cajas de Aluminio|01|test|test|DenominacionGenericaProd1|DenominacionDistintivaProd1|Fabricante1|2028-01-01|LoteMedic1|01|01|RegistroSanita1|321|ASDASD321|321asd|asdedasd5|65as4d|65a4sd6|100|1|MXN|0E94D982-ECFD-46F3-8648-CCD38B34E6A7|1|OR101010|DE202020|TPAF01|1|VL|1|qwe1232|2019|GNP|ds22241s|CTR004|VL45K98|01|EKU9003173C9|213122534|Jorge Gomez Junco|02|CACX7605101P8|Propietario|PT01||
 Gracias

**Comment by eclipxe13** [comment]
CfdiUtils por defecto toma los archivos del SAT tal como están publicados para generar la cadena de origen
El SAT aún no incluye el archivo XSLT del CPP 3.0 en la herramienta de CFDI 4.0 para generar la cadena original.
Probablemente esto ocurrirá el 25 de noviembre, cuando entre en vigor el CCP 3.0.

Mientras tanto, puedes usar el `XmlResolver` apuntando a una copia local y modificar `cadenaoriginal_4_0.xslt` para que incluya `CartaPorte30.xslt`.

http://www.sat.gob.mx/sitio_internet/cfd/CartaPorte/CartaPorte30.xslt
http://www.sat.gob.mx/sitio_internet/cfd/4/cadenaoriginal_4_0/cadenaoriginal_4_0.xslt

**Comment by eclipxe13** [comment]
La conversación que se dio al respecto en discord hace 10 días: https://discord.com/channels/459860554090283019/459860554677354537/1172715149816250438

**Comment by eclipxe13** [comment]
Ahora sí, el SAT ya puso CPP 3.0 en el XSLT de CFDI 4.0: https://github.com/phpcfdi/resources-sat-xml/commit/88c01606685fb387556b92cbff78db48971468cc
