### ISSUE TITLE
Validacion de elemento Addenda

### ISSUE THREAD

**Issue by AlonsoIbarra** [eclipxe13/CfdiUtils#120]
Hola tengo un problema con la validacion de un xml el cual contiene un elemento addenda de esta manera, 
  <cfdi:Addenda>
    <ad:ADENDAS xmlns:ad="http://www.addenda.com">
      <ad:CAB LABEL="CABADD" TIPO_DOC="1" CODIGO_FUF="20231122C010K01P00" PERIODO_ECD="2024-03-20" FECHA_LIM_PAGO="" ID_PARTIC_CENACE="C010K01" BANCO="Bancomer" SUCURSAL="No.2" CUENTA="123457891234567891112234" CLAVE="123457891234567891" REF_BANCO="1234578912345" CONTACTO="contacto@mail.com" IMPORTE_TOTAL="118270.96" MONTO_LETRA="CIENTO DIECIOCHO MIL DOSCIENTOS SETENTA con 96/100">
        <ad:Conceptos>
          <ad:LINEA LABEL="linadd" NUM_LIN="1" FOLIO_UNICO="A012" CONCEPTO="xyz" Cantidad="2" Unidad="KG" PrecioUnit="12.03" ImporteLinea="24.06" Iva="16" Total="30.06"/>
        </ad:Conceptos>
      </ad:CAB>
    </ad:ADENDAS>
  </cfdi:Addenda>
y el validador me regresa el error "Schema validation failed: Element '{http://www.addenda.com}ADENDAS': No matching global element declaration available, but demanded by the strict wildcard.", he estado investigando y cambiando la estructura de la addenda pero siempre regresa error en el primer child de la Addenda. Estoy usando la version 4.0 de cfdi.

**Comment by eclipxe13** [comment]
Es correcto, falla la validación de esquemas por que no puede validar el namespace "http://www.addenda.com" al no tener una defición de XSD. Esto no es por la librería es por que el SAT así lo exige en el Anexo 20 y con los XSD de CFDI.

Lamentablemente, el SAT también aconseja integrar la Addenda **después de timbrar**, con lo que este tipo de errores son comunes. Para ello, te recomiendo usar [phpcfdi/cfdi-cleaner](https://github.com/phpcfdi/cfdi-cleaner) antes de validar, que entre sus múltiples limpiadores tiene uno que remueve la addenda. De hecho, te recomiendo siempre limpiar los CFDI recibidos con [phpcfdi/cfdi-cleaner](https://github.com/phpcfdi/cfdi-cleaner) que corrige varios errores comunes que hemos encontrado en la comunidad de PhpCfdi.

Nota: La addenda puede ser removida por que no pertenece a la cadena de origen, ver: <https://cfdiutils.readthedocs.io/es/latest/componentes/cadena-de-origen.html#cadena-de-origen>.

**Comment by AlonsoIbarra** [comment]
Ho, muchas gracias por tu ayuda @eclipxe13.
