### ISSUE TITLE
Como parsear un cfdi v. 3.3

### ISSUE THREAD

**Issue by antonioalvarezm** [eclipxe13/CfdiUtils#32]
Tienes un ejemplo de como parsear un cfdi v. 3.3?

**Comment by eclipxe13** [comment]
A qué te refieres con parsear? Leer el contenido de un Cfdi y recorrer sus datos o buscar una información específica? No :disappointed:. Me acabo de dar cuenta que en el wiki este documento está pendiente! Lo escribo pronto. Mientras tanto:

* Puedes abrir un Cfdi usando el método `$cfdi = \CfdiUtils\Cfdi::newFromString($xmlString);`.
* La forma de acceder al contenido es por medio de [Nodos](https://github.com/eclipxe13/CfdiUtils/wiki/Nodes) y tienes el nodo principal `<cfdi:Comprobante>` desde `$comprobante = $cfdi->getNode()`
* Después, si quieres un valor del nodo simplemente entras a él como un arreglo, por ejemplo, para obtener el atributo folio solo debes `$folio = $comprobante['Folio']`
* Usa los [métodos de búsqueda](https://github.com/eclipxe13/CfdiUtils/wiki/Nodes#m%C3%A9todos-de-b%C3%BAsqueda) para acceder a nodos hijos más fácil: `$conceptos = $comprobante->searchNodes('cfdi:Conceptos', 'cfdi:Concepto')`

Si gustas mira en este proyecto para ver cómo está recorriendo el contenido del Cfdi para generar un HTML (que luego será convertido a PDF): https://github.com/phpcfdi/cfditopdf/blob/master/templates/generic.php

Te recomiendo que en lugar de abrir un issue platiquemos en [el canal de gitter](https://gitter.im/eclipxe13/php-cfdi), generalmente estoy en horarios de trabajo. Hay otros usuarios y yo que te podemos ayudar y platicar más fácil que dentro de github.

**Comment by eclipxe13** [comment]
He creado un artículo wn el wiki que habla de cómo leer un cfdi y la clase específica `CfdiUtils\Cfdi`: https://github.com/eclipxe13/CfdiUtils/wiki/Leer-cfdi

Junto con la información de [Nodos](https://github.com/eclipxe13/CfdiUtils/wiki/Nodes) debe ser suficiente para parsear o procesar un cfdi.
