### ISSUE TITLE
Duda: CFDI de tipo I/E con complemento de recepción de pagos

### ISSUE THREAD

**Issue by eclipxe13** [eclipxe13/CfdiUtils#34]
Duda contable: Técnicamente es posible emitir un CFDI de tipo I o E e incluir el complemento de pago en el mismo comprobante (sin establecer en el complemento documentos relacionados ni impuestos).
**La duda es: Cuál es el caso en donde esto puede suceder?**
- No es en el caso de anticipos, dado que un anticipo es un PUE
- No es el caso de pago al momento de la operación, dado que es un PUE

**Comment by TheSpectroMx** [comment]
Si siguiéramos las reglas de facturación es imposible que se llegue a dar el caso. De entrada en teoría un tipo de comprobante E no puede ser relacionada en un complemento de pago, pongo en teoría porque he visto complementos de pago que relacionan comprobantes tipo E.

Ahora bien en resumen todo lo que sea un PUE no lleva complemento de pago, todo lo que sea PPD es lo que lleva complemento de pago.

**Comment by eclipxe13** [comment]
Gracias, en corto: en la práctica es un caso imposible.
