### ISSUE TITLE
comprobante de pago

### ISSUE THREAD

**Issue by Yorchi** [eclipxe13/CfdiUtils#35]
Hola que tal, 

queria ver si me pueden ayudar con algun ejemplo de como agregar el complemento de pago.

Espero su ayuda y muchas gracias.

**Comment by eclipxe13** [comment]
```php
$complementoPagos = new \CfdiUtils\Elements\Pagos10\Pagos();
// ...
$comprobante->addComplemento($complementoPagos);
```

No voy a cerrar este issue porque hay que documentar de forma genérica la creación e inclusión de complementos, así como la documentación específica del complemento de recepción de pagos.

**Comment by eclipxe13** [comment]
He documentado en https://github.com/eclipxe13/CfdiUtils/wiki/Agregar-Complementos la forma de agregar complementos que no tienen un espacio de nombres definido en `CfdiUtils\Elements`.
