### ISSUE TITLE
SUMAS06: False positive with sums

### ISSUE THREAD

**Issue by eclipxe13** [eclipxe13/CfdiUtils#38]
El el siguiente CFDI se genera este error:
```
El importe del impuesto Grupo traslado Impuesto 002 Tipo factor Tasa Tasa o cuota 0.160000 es igual a el importe del nodo.
Calculado: 51.86, Encontrado: 51.86207
```
Por lo tanto, el cálculo del importe de la suma de los impuestos trasladados es incorrecto o bien no debería redondearse.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd" Version="3.3" Fecha="2018-06-29T07:36:18" Total="376" SubTotal="324.14" Moneda="MXN" TipoCambio="1" Certificado="..." FormaPago="01" NoCertificado="00001000000305747164" TipoDeComprobante="I" LugarExpedicion="44610" Serie="BB" Folio="978903" MetodoPago="PUE" Sello="UPl9dKr7oa2pguvaA/4L3FlnTNLrCgxAILRXSx2oYmq1S5iCAlh8814Wut/mXYwhxLSkFksDx2VjuyVdpi9e+v4NOzBAZk0wPMBcaKnj9fhgnGFJGvDczJ22/7Yq/4F0RKupk3jt/CWwmSH6Nta8GYUxHrOtGzYGMDZnyjVszes=">
  <cfdi:Emisor RegimenFiscal="601" Nombre="RED DE CARRETERAS DE OCCIDENTE SAB DE CV" Rfc="RCO0708136F7"/>
  <cfdi:Receptor Nombre="DAY INTERNATIONAL DE MEXICO SA DE CV" Rfc="DIM8701081LA" UsoCFDI="P01"/>
  <cfdi:Conceptos>
    <cfdi:Concepto Cantidad="1.000000" Descripcion="PEAJE EN EFECTIVO CORRESPONDIENTE AL CRUCE DE NRU: 0180510004916289A09A511E2C097A78 FECHA: 26/06/0018 HORA: 11:17:45 CASETA: LEON CLASE: A" ValorUnitario="39.655172" Importe="39.655172" Unidad="SERVICIO" NoIdentificacion="0180510004916289A09A511E2C097A78" ClaveUnidad="E48" ClaveProdServ="95111500">
      <cfdi:Impuestos>
        <cfdi:Traslados>
          <cfdi:Traslado Importe="6.344828" TasaOCuota="0.160000" TipoFactor="Tasa" Impuesto="002" Base="39.655172"/>
        </cfdi:Traslados>
      </cfdi:Impuestos>
    </cfdi:Concepto>
    <cfdi:Concepto Cantidad="1.000000" Descripcion="PEAJE EN EFECTIVO CORRESPONDIENTE AL CRUCE DE NRU: 018062000477388671A49097D0622D1F FECHA: 26/06/0018 HORA: 19:03:26 CASETA: LEON CLASE: A" ValorUnitario="39.655172" Importe="39.655172" Unidad="SERVICIO" NoIdentificacion="018062000477388671A49097D0622D1F" ClaveUnidad="E48" ClaveProdServ="95111500">
      <cfdi:Impuestos>
        <cfdi:Traslados>
          <cfdi:Traslado Importe="6.344828" TasaOCuota="0.160000" TipoFactor="Tasa" Impuesto="002" Base="39.655172"/>
        </cfdi:Traslados>
      </cfdi:Impuestos>
    </cfdi:Concepto>
    <cfdi:Concepto Cantidad="1.000000" Descripcion="PEAJE EN EFECTIVO CORRESPONDIENTE AL CRUCE DE NRU: 0180410000070284E442D19AE5862434 FECHA: 28/06/0018 HORA: 08:35:32 CASETA: LEON CLASE: A" ValorUnitario="122.413793" Importe="122.413793" Unidad="SERVICIO" NoIdentificacion="0180410000070284E442D19AE5862434" ClaveUnidad="E48" ClaveProdServ="95111500">
      <cfdi:Impuestos>
        <cfdi:Traslados>
          <cfdi:Traslado Importe="19.586207" TasaOCuota="0.160000" TipoFactor="Tasa" Impuesto="002" Base="122.413793"/>
        </cfdi:Traslados>
      </cfdi:Impuestos>
    </cfdi:Concepto>
    <cfdi:Concepto Cantidad="1.000000" Descripcion="PEAJE EN EFECTIVO CORRESPONDIENTE AL CRUCE DE NRU: 0185320002694707AFDE353139DF224E FECHA: 28/06/0018 HORA: 20:55:02 CASETA: LEON CLASE: A" ValorUnitario="122.413793" Importe="122.413793" Unidad="SERVICIO" NoIdentificacion="0185320002694707AFDE353139DF224E" ClaveUnidad="E48" ClaveProdServ="95111500">
      <cfdi:Impuestos>
        <cfdi:Traslados>
          <cfdi:Traslado Importe="19.586207" TasaOCuota="0.160000" TipoFactor="Tasa" Impuesto="002" Base="122.413793"/>
        </cfdi:Traslados>
      </cfdi:Impuestos>
    </cfdi:Concepto>
  </cfdi:Conceptos>
  <cfdi:Impuestos TotalImpuestosTrasladados="51.86">
    <cfdi:Traslados>
      <cfdi:Traslado Importe="51.862070" TasaOCuota="0.160000" TipoFactor="Tasa" Impuesto="002"/>
    </cfdi:Traslados>
  </cfdi:Impuestos>
</cfdi:Comprobante>

```

**Comment by eclipxe13** [comment]
El atributo en cuestión se trata de `cfdi:Comprobante/cfdi:Impuestos/cfdi:Traslados/cfdi:Traslado@Importe` y `cfdi:Comprobante/cfdi:Impuestos/cfdi:Retenciones/cfdi:Retencion@Importe`.

Según el Anexo 20, para:

* `cfdi:Traslado@Importe`: *Atributo requerido para señalar la suma del importe del impuesto trasladado, agrupado por impuesto, TipoFactor y TasaOCuota. No se permiten valores negativos.*
* `cfdi:Retencion@Importe`: *Atributo requerido para señalar la suma del importe del impuesto trasladado, agrupado por impuesto, TipoFactor y TasaOCuota. No se permiten valores negativos.*

El campo debe contener la suma de los traslados (o retenciones) expresados en los impuestos de los conceptos, con un máximo de 6 decimales. Los atributos que suma (los de los conceptos) son del tipo `t_Importe` que admiten hasta 6 decimales y no se especifica que __deban__ ser redondeados, aunque __pueden__ ser redondeados.

Por lo anterior, entonces la case `\CfdiUtils\SumasConceptos\SumasConceptos` no debe redondear la suma de los importes de los impuestos en los conceptos. La suma se debe considerar con toda la carga de decimales que resulte.

No así para los atributos `totalImpuestosTrasladados` y `totalImpuestosRetenidos` del nodo `Impuestos` del `Comprobante`. En este caso está definido que la suma debe ser redondeada a la cantidad de decimales que admita la moneda.

A su vez, en este proyecto la generación de las sumas es diferente a la escritura de estas mismas. La escritura se puede hacer manualmente o con la ayuda de la clase `CfdiUtils\Elements\Cfdi33\Helpers\SumasConceptosWriter` y dicha clase tiene sus propias reglas. Ver issue #41

**Comment by eclipxe13** [comment]
Acabo de ver la hoja 72 y 73 del Anexo 20 y explícitamente dice que dichos atributos **deben tener hasta la cantidad de decimales que soporte la moneda** por lo que este issue no es válido.

**Comment by eclipxe13** [comment]
Agregar a `CfdiUtils\Validate\Cfdi33\Standard\ComprobanteImpuestos` que valide que los atributos `TotalImpuestosTrasladados`, `TotalImpuestosRetenidos` y en sus hijos `Traslados\Traslado` y `Retenciones\Retencion` los valores no tengan más decimales que los que admite la moneda.

**Comment by uziel200** [comment]
Todo un caso los redondeos, pero el SAT permite que a nivel detalle `cfdi:Comprobante/cfdi:conceptos` se puedan usar hasta 6 decimales y a nivel encabezados `cfdi:Comprobante@subtotal` o totales de impuestos`cfdi:Comprobante/cfdi:Impuestos` se utilicen los decimales de la moneda, en caso de MXN has 2 decimales.

Para realizar la validación de las diferencias que pueda existir por el redondeo de decimales el SAT solicita a los PACs que realicen un calculo de límite inferior y limité superior.

Pueden consultar la página 68 del siguiente documento:

[Estándarcfdv33.pdf](https://github.com/eclipxe13/CfdiUtils/files/2182973/Estandarcfdv33.pdf)

Pero insito, es totalmente válido que a nivel detalle se manejen hasta 6 decimales y los totales o agrupaciones de impuestos si se deben de redondear a los decimales de la moneda

**Comment by uziel200** [comment]
Lo olvidaba, el sustento legal para manejar 6 decimales en el detalle, 2 en los totales y globales, lo pueden consultar directamente en el SAT en el documento llamado guía de llenado:

http://omawww.sat.gob.mx/informacion_fiscal/factura_electronica/Paginas/Anexo_20_version3.3.aspx 

**Guía de llenado:**

* Totales: página 8
* Nodo de Conceptos: página 17

http://omawww.sat.gob.mx/informacion_fiscal/factura_electronica/Documents/Gu%C3%ADaAnexo20.pdf

**Comment by eclipxe13** [comment]
Así es. Gracias por la documentación.

El problema descrito aquí es en el concentrado de los impuestos a nivel de comprobante, no a nivel de conceptos.

Este issue de cerrará en cuanto tenga el tiempo de hacer un validador sobre dichos nodos que deben ser redondeados hasta la cantidad de decimales que soporte la moneda.
