### ISSUE TITLE
pem file error

### ISSUE THREAD

**Issue by aldolinares** [eclipxe13/CfdiUtils#42]
Hi I get: The key is not a file or a string PEM format private key

but the pem file have in headers: 

-----BEGIN RSA PRIVATE KEY-----

What could be the problem?

**Comment by eclipxe13** [comment]
How are you writing the path to the file? Or.. are you  passing the file contents? Can you give us a code example please?

**Comment by aldolinares** [comment]
That was the problem it was that the path was wrong without "file:/"

it's fixed now.

**Comment by eclipxe13** [comment]
Nice! Let me close this issue after add some documentation about this missuse, I think is the second time it happened.
