### ISSUE TITLE
Impuestos Order Error

### ISSUE THREAD

**Issue by aldolinares** [eclipxe13/CfdiUtils#43]
Hi 

I have an error when I try to "timbrar" an XML with retenciones and traslados, If i look at the XML file I can see that the order for impuestos is wrong, I am getting first the Traslados and then the Retenciones. 

Original text (Failes to Timbrar):
  <cfdi:Impuestos TotalImpuestosTrasladados="160.00" TotalImpuestosRetenidos="100.00">
    <cfdi:Traslados>
      <cfdi:Traslado Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="160.00"/>
    </cfdi:Traslados>
    <cfdi:Retenciones>
      <cfdi:Retencion Impuesto="001" Importe="100.00"/>
    </cfdi:Retenciones>
  </cfdi:Impuestos>

And if a change the XML file and try to "timbrar" it goes fine:
  <cfdi:Impuestos TotalImpuestosTrasladados="160.00" TotalImpuestosRetenidos="100.00">
    <cfdi:Retenciones>
      <cfdi:Retencion Impuesto="001" Importe="100.00"/>
    </cfdi:Retenciones>
    <cfdi:Traslados>
      <cfdi:Traslado Impuesto="002" TipoFactor="Tasa" TasaOCuota="0.160000" Importe="160.00"/>
    </cfdi:Traslados>
  </cfdi:Impuestos>

I see that I can change the orden on Impuestos, but this also change the order on conceptos and it fails too. 

Not sure if this is a validation by my timbres service provider or if this is really a bug

**Comment by aldolinares** [comment]
Hi Carlos, I did try to change the file and test it, but the order also changes in impuestos node inside of conceptos and it fails to Timbrar algo. 

I'am trying to understend your code to see if I can find how to fix it. 

Thank you

**Comment by eclipxe13** [comment]
You are right:

- In the case of `Impuestos` inside `Concepto` the first children node should be `Traslados`
- In the case of `Impuestos` inside `Comprobante` the first children node should be `Retenciones`

I hate this inconsistencies... The only way I can think to repair this is to create a separated class (extented class named `ImpuestosConceptos`) that overrides the order...

A work around -before library is updated- could be to override the order... something like:

```php
/** @var CfdiCreator33 $creator */
$creator->addSumasConceptos(null, 2);
// change the order of the comprobante/impuestos after sums are added
$creator->comprobante()->getImpuestos()->children()->setOrder(['cfdi:Retenciones', 'cfdi:Traslados']);
```

**Comment by eclipxe13** [comment]
btw... I'm thinking about the fixing... is you want to share ideas or understand the code better we can chat in gitter <https://gitter.im/eclipxe13/php-cfdi>

**Comment by eclipxe13** [comment]
Thanks to @ircsasw to report that this is also present in `pagos10:Impuestos`

- In the case of `Impuestos` inside `pagos10:Pagos` the first children node should be `Retenciones`

**Comment by aldolinares** [comment]
I think creating a separated class is the way to go, for any future changes.

**Comment by eclipxe13** [comment]
@aldolinares Thanks for your finding! this has been solved. If you are using thins library I suggest you to join <https://gitter.im/eclipxe13/php-cfdi>, beers are free!
