### ISSUE TITLE
Validation Timeout

### ISSUE THREAD

**Issue by aldolinares** [eclipxe13/CfdiUtils#44]
Hi today doing some test, When I was trying to "timbrar" an XML got time out, and after removing the validation code: $asserts = $creator->validate(); Everything was fine. 

I still haven't seen that particular code for validation, I will get back if I have some more information. 

Thank you Carlos

**Comment by eclipxe13** [comment]
Ok, make sure that you are using the updated library.

As you can see in the last release (from yesterday) we made some improvements and integrate with AppVeyor that contains MS Windows continuous integration.

Are you using MS Windows? Mac? GNU/Linux?

How are you configuring your `CfdiCreator33`?

Are you changing the `XmlResolver` or the `XsltBuilder`?

As the problem you describe... it looks like that it get staled in some point, it might be when try to download a resource from internet. Remember that you can setup a different `DownloaderInterface`, by default it uses `PhpDownloader` that simply try to copy an HTTP resource to the local directory.

You might want to create a ` PhpDownloaderWithLog`, something like:

```php
<?php
namespace MyProject;

use XmlResourceRetriever\Downloader\PhpDownloader;

class PhpDownloaderWithVarDump extends PhpDownloader
{
    public function downloadTo(string $source, string $destination)
    {
        // do the log/debug as you consider more optimal
        var_dump(date('c') . " before downloading $source into $destination");
        parent::downloadTo($source, $destination);
        var_dump(date('c') . " after downloading $source into $destination");
    }
}
```

And use it in your creator:

```php
<?php
$creator = new \CfdiUtils\CfdiCreator33();
// override the default downloader:
$creator->getXmlResolver()->setDownloader(new \MyProject\PhpDownloaderWithVarDump());
```

**Comment by aldolinares** [comment]
Sorry I didn't respond to this request, it's working fine
