### ISSUE TITLE
Timbrado de CFDI 3.3

### ISSUE THREAD

**Issue by edusl2495** [eclipxe13/CfdiUtils#45]
Hola que tal, soy nuevo en esto de generar facturas y más cuando deben ser con formato válido del SAT, da la casualidad que me lo asignaron como proyecto, buscando y buscando di con tu código que me parece excelente, pero tengo dudas en cuanto como se debe proceder el timbrado del XML una vez creado y como validarlo, estuve buscando en la [documentacion](https://cfdiutils.readthedocs.io/es/latest/) pero no he encontrado esa parte. Agradezco de antemano tu respuesta.
Saludos.

**Comment by eclipxe13** [comment]
Bienvenido!

El timbrado está fuera del alcance de este proyecto, si gustas estamos en [https://gitter.im/eclipxe13/php-cfdi](https://gitter.im/eclipxe13/php-cfdi?utm_source=share-link&utm_medium=link&utm_campaign=share-link) y ahí te podemos orientar de cómo timbramos. Esto es básicamente porque los proveedores de timbrado tienen diferentes implementaciones y características que no permiten tener una implementación genérica.

**Comment by edusl2495** [comment]
oh ya veo, te agradezco la info
claro, teniendo tiempo me doy una vuelta por el chat.
