### ISSUE TITLE
Tasa Exento

### ISSUE THREAD

**Issue by aldolinares** [eclipxe13/CfdiUtils#46]
Buen dia, 

Al agregar un impuesto exento crea el CFDI sumando los traslados sin valor

  <cfdi:Impuestos TotalImpuestosTrasladados="0.00">
    <cfdi:Traslados>
      <cfdi:Traslado Impuesto="002" TipoFactor="Exento" TasaOCuota="" Importe="0.00"/>
    </cfdi:Traslados>
  </cfdi:Impuestos>

Lo cual genera un error en TasaOCuota el cual deberia ser 0.00000

**Comment by eclipxe13** [comment]
Tienes razón. De la página 33 de la guía de llenado de CFDI dice:

* Para `Comprobante/Impuestos/Traslados`
> En el caso de que sólo existan conceptos en el CFDI con un TipoFactor exento, este nodo no debe existir.

De ahí infiero que no se debe listar en absoluto los excentos dentro de `Comprobante/Impuestos/Traslados`. **¿qué opinas?**

Estoy diseñando un caso que demuestre el bug para después solucionarlo.

**Comment by aldolinares** [comment]
Gracias por responder. 

Los que revise reales todos manejaban en 0.000000 si tienen el nodo. 

El error al timbrarlo en este momento es porque no tiene dato alguno TasaOCuota, podrias guiarme mas o menos donde tienes el codigo para ver si puedo repararlo rapido seria de gran ayuda, no le he buscado aun.

**Comment by eclipxe13** [comment]
Para poner `0.000000` después de establecer las sumas:

```php
<?php
/** @var CfdiCreator33 $creator */
// ... creación del cfdi con todos sus datos ...

// .. crear las sumas y escribirlas en el comprobante ...
$creator->addSumasConceptos(null, 2);

// hacer esto después de llamar a addSumasConceptos
$comprobante = $creator->comprobante();
foreach ($comprobante->searchNodes('cfdiImpuestos', 'cfdi:Traslados', 'cfdi:Traslado') as $traslado) {
    if ('Exento' === $traslado['TipoFactor']) {
        $traslado['TasaOCuota'] = '0.000000';
    }
}

// continuar con la creación ...
$creator->addSello('file:// ... archivo.pem ...', 'password');
// ...
```

Aunque no creo que esto sea la solución final dado que se es explícito en omitir todos los traslados si solo hay exentos... yo creo que tal cual se deben omitir los exentos del resumen.

**Comment by eclipxe13** [comment]
Si vas para https://gitter.im/eclipxe13/php-cfdi ahí podemos revisar de forma más rápida

**Comment by eclipxe13** [comment]
Revisa por favor si la rama [development](https://github.com/eclipxe13/CfdiUtils/tree/development) te funciona.

CHANGELOG: https://github.com/eclipxe13/CfdiUtils/blob/development/docs/CHANGELOG.md#version-276-2019-01-16

**Comment by eclipxe13** [comment]
Después de un análisis más detallado y de encontrar en el Anexo 20 y en la matriz de errores de CFDI versión 3.3 la regla **CFDI33193** que dice acerca de `Comprobante/Impuestos/Traslados/Traslado@TasaOCuota`:

> *El valor seleccionado debe corresponder a un valor del catalogo donde la columna impuesto corresponda con el campo impuesto y la columna factor corresponda con el campo TipoFactor.*

Al no existir en el catálogo `c_TasaOCuota` ningún valor referido a `Exento` entonces simplemente se ignoran este tipo de traslados.

Esto nos lleva a que si dentro de los conceptos solo existen traslados de tipo exento entonces todos serán ignorados, por lo que no se creará el nodo `Comprobante/Impuestos/Traslados` y tampoco se creará el atributo `Comprobante/Impuestos@TotalImpuestosTrasladados`.

Por lo que este reporte está corregido desde el [tag v2.7.6](https://github.com/eclipxe13/CfdiUtils/tree/v2.7.6). Gracias!
