### ISSUE TITLE
Leer campos Total y SubTotal de un tipo de comprobante P retornan vacíos 

### ISSUE THREAD

**Issue by jaimeres** [eclipxe13/CfdiUtils#48]
Al leer los campos Total y SubTotal de un complemento de pago (tipo de comprobante = P) el resultado es una cadena vacía

```
$c = \CfdiUtils\Cfdi::newFromString(file_get_contents('comp.xml'))
   ->getQuickReader();
echo $c['TipoDeComprobante'];
echo isset($c['Total']) ? "existe ".$c['Total']: "no existe ".$c['Total'];
echo isset($c['SubTotal']) ? "existe ".$c['SubTotal']: "no existe ".$c['SubTotal'];
echo  isset($c['Moneda']) ? "existe ".$c['Moneda']: "no existe ".$c['Moneda']; ``
```
![123 fw](https://user-images.githubusercontent.com/19354871/55765209-41306280-5a34-11e9-9953-f0e30f744217.png)

Imprime
P
------------------------------------
existe 
------------------------------------
existe 
------------------------------------
existe XXX

**Comment by eclipxe13** [comment]
Gracias! Confirmo que pude crear un test que prueba este comportamiento. Estoy investigando qué sucede.

**Comment by eclipxe13** [comment]
Estoy por publicar la versión 2.10.2 que soluciona el problema:

La causa es un error en `QuickReader`, al retornar los valores que se pueden interpretar como falsos, en lugar de devolver el valor, devuelve una cadena de caracteres vacía.

**Comment by eclipxe13** [comment]
Listo, he liberado la versión 2.10.2 que corrige el problema que reportas.
Actualiza tu versión con `composer update eclipxe/cfdiutils`.
Recuerda consultar la documentación de **[`QuickReader`](https://cfdiutils.readthedocs.io/es/latest/leer/quickreader/)**
Gracias!
