### ISSUE TITLE
Addendas

### ISSUE THREAD

**Issue by carrguerr** [eclipxe13/CfdiUtils#49]
Buena tarde, estoy teniendo el detalle que, cuando las facturas a validar de estructura tienen un addenda particular, no puede descargar o validar esto. Manda error de descarga y para en el resto de la validación.

**Comment by eclipxe13** [comment]
Hola!!

Lo más probable, como dices, es que el XSD de la Addenda no fue declarado en el XML o bien no está disponible. Por lo tanto, la validación de que el XML cumple con los XSD falla.

Lo malo de las addendas es que muchas veces no están bien definidas o no tienen un XSD.

Lo bueno es que no pertenecen a la cadena de origen, por lo tanto se pueden quitar del CFD y validar únicamente la parte interesante.

Para quitar las addendas y corregir otros errores que _no afectan la cadena de origen_ puedes usar el limpiador de Cfdi <https://cfdiutils.readthedocs.io/es/latest/leer/limpieza-cfdi/> y de esta manera no preocuparte por su contenido.

**Comment by carrguerr** [comment]
Si de hecho , tengo tres facturas que tienen addenda pero no estan declarados, de volaris. Ok voy a limpiarlos para quitar de problemas, incluso OfficeDepot salen esos errores.
