### ISSUE TITLE
Almacenamiento local de recursos del SAT

### ISSUE THREAD

**Issue by AlonsoCauich** [eclipxe13/CfdiUtils#50]
A la hora de realizar el almacenamiento local para archivos del SAT me marca una respuesta message: "The payload is invalid.", exception: "Illuminate\Contracts\Encryption\DecryptException

No descarga el timbrefiscaldigital. Tienen alguna solución?

**Comment by eclipxe13** [comment]
Hola Alonso.

Desconozco el problema que tienes. Lo que te puedo asegurar es que la librería no tiene ninguna dependencia con Laravel, por lo que creo que tu error está en el uso que le estás dando.

Ojalá nos puedas dar más información para el historial de este issue.
