### ISSUE TITLE
Como puedo agregar el timbre fiscal

### ISSUE THREAD

**Issue by miguelcenteno** [eclipxe13/CfdiUtils#52]
No encuentro un ejemplo en donde indique como agregar el timbre fiscal al comprobante. Me puedes orientar por favor?

**Comment by eclipxe13** [comment]
El timbre fiscal digital lo agrega el PAC cuando timbra el comprobante.

Sin embargo, si lo que quieres es agregarlo tu (porque tienes los datos o porque lo estás simulando) lo puedes hacer como se agrega cualquier complemento.

https://cfdiutils.readthedocs.io/es/latest/crear/complementos-aun-no-implementados/

Y puedes usar la clase de ayuda `CfdiUtils\Elements\Tfd11\TimbreFiscalDigital`.

Aquí hay un ejemplo donde se ejemplifica el caso:

https://github.com/eclipxe13/CfdiUtils/blob/master/tests/CfdiUtilsTests/UseCases/ReadCfdiWithTimbreOnSecondComplementoTest.php#L144

**Comment by ircsasw** [comment]
Los dos PAC que he usado regresan el XML con todo y el Timbre si es que el comprobante se pudo timbrar pero se que no todos los PAC lo hacen, hay PAC que regresan sólo los datos del timbre, en ese caso es como te dice @eclipxe13; pero yo te recomiendo que si tu PAC te regresa el XML ya con el timbre pues uses ese ya como tu XML definitivo.

Te invito al canal de Discord si quieres comentar más del tema:
https://discord.gg/e79Cc6A

**Comment by miguelcenteno** [comment]
Muchas gracias @eclipxe13 e @ircsasw, justo lo que necesitaba era realizar la simulación de timbrado.

**Comment by eclipxe13** [comment]
en ese caso aquí una respuesta más directa:
```php
        $comprobante->addComplemento(
            new TimbreFiscalDigital([
                'UUID' => '00000000-0000-0000-0000-000000000000',
                'FechaTimbrado' => '2019-01-13T14:15:16',
                'RfcProvCertif' => 'AAA010101XX1',
                'NoCertificadoSAT' => '00000000000000000000',
                'SelloCFD' => str_repeat('A', 172) . '=',
                'SelloSAT' => str_repeat('B', 172) . '=',
            ])
        );
```
