### ISSUE TITLE
Complemento nomina

### ISSUE THREAD

**Issue by miguelcenteno** [eclipxe13/CfdiUtils#53]
Tienen implementado el complemento de nomina?

Saludos!!

**Comment by eclipxe13** [comment]
No está implementado. No hay elementos de ayuda y tampoco hay validadores
específicos.

Pero sí puedes crear comprobantes con el complemento de nómina usando el
objeto Node genérico.

Creo que en el canal de discord hay quienes ya lo han hecho. Y estamos
abiertos a PR que puedan ser útiles a la comunidad.

**Comment by eclipxe13** [comment]
Por favor, no cierres este issue. De esta manera podemos ver si en la comunidad es necesario y planear su implementación.

**Comment by miguelcenteno** [comment]
Va que va, pues de hecho ya lo ando armando, si les sirve se los comparto. Lo que si no creo poder hacer es el validador, si esta medio complicado jeje.

**Comment by miguelcenteno** [comment]
Corrección, me di cuenta que sin los validadores no es posible que se genere el cfdi. Hice las validaciones para que pasara el xml y se timbrará pero la verdad no tiene todas la validaciones del bien implementadas, pero si te sirve como base, con mucho gusto te paso mi implementación para la comunidad, esta excelente tu código.

**Comment by eclipxe13** [comment]
Sin los validadores no se puede generar el cfdi?
Hay alguna regla que falle así como está? Porque no debería.

Con avance que tengas podríamos empezar a trabajar. Tienes un fork?

**Comment by miguelcenteno** [comment]
Tuve que modificar el validador de método de pago y forma de pago por que me marcaba errores al validar. Pero no me di el tiempo de revisar a detalle la guía de llenado, me base en uno de los que ya genero en otra aplicación. No tengo un fork, baje el master y lo modifique de forma local.

**Comment by eclipxe13** [comment]
Sería excelente que nos comentaras los errores que obtuviste para hacer las correcciones necesarias que permitan generar el CFDI de Nómina.

Si gustas, en el chat de discord https://discord.gg/aFGYXvX podemos ver el tema de forma más dinámica.

**Comment by eclipxe13** [comment]
El día de hoy he agregado los elementos de ayuda para crear el CFDI de Nómina.
