### ISSUE TITLE
Inyectar comprobante a la clase CfdiCreator33

### ISSUE THREAD

**Issue by sivegm77** [eclipxe13/CfdiUtils#55]
Tengo un objeto $cfdi = \CfdiUtils\Nodes\XmlNodeUtils::nodeFromXmlString($content);
y un objeto $creator = new CfdiCreator33();
Como puedo inyectar el objeto cfdi en el objeto creator? Hay alguna manera de convertir una clase "Node" a  "Comprobante"?

**Comment by eclipxe13** [comment]
Respuesta corta: no hay una traducción directa entre el objeto que lee CFDI y el objeto que escribe CFDI. Esto es porque el que lee carga la información en Nodos y el que escribe usa Elementos, que son Nodos sobrecargados con métodos de ayuda.

Ahora bien. Dado que los Nodos son editables es posible alterar el contenido y después explotarlo a XML nuevamente. La desventaja es que ya no tendrías disponible los métodos de ayuda del comprobante.

Otra forma de hacerlo sería crear un traductor. Que a partir de la información que va leyendo del CFDI sea capaz de recrear la clase Comprobante y te lo devuelva.

No lo tiene actualmente pero no es imposible. No he visto este caso de uso, ¿Para qué lo ocupas?

**Comment by sivegm77** [comment]
Hola. Lo solucione con de esta forma:
        $cfdi = \CfdiUtils\Nodes\XmlNodeUtils::nodeFromXmlString($content);
        return new self(CfdiCreator33::newUsingNode($cfdi));

De esta forma puedo setear nuevos atributos a un CFDI.
Gracias por la respuesta.
