### ISSUE TITLE
informacion de schemalocation complemento de pago

### ISSUE THREAD

**Issue by aumeli74** [eclipxe13/CfdiUtils#56]
Al crear un complemento de pago:
  $comprobanteAtributos = [
                'xmlns:cfdi' => "http://www.sat.gob.mx/cfd/3",
                'xmlns:xsi' => "http://www.w3.org/2001/XMLSchema-instance",
                'xsi:schemaLocation' => "http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/Pagos http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos10.xsd" ,
                'xmlns:pago10' =>  "http://www.sat.gob.mx/Pagos",

la funcion de            
    $xml_content = $creator->asXml();

regresa schemalocation con las 2 primeras partes unicamente ,

 xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd"
    xmlns:pago10="http://www.sat.gob.mx/Pagos"

**Comment by eclipxe13** [comment]
Así es, en realidad no es necesario que agregues las definiciones de namespaces `xmlns:cfdi'`, `xmlns:pago10`, `xmlns:xsi` ni `xsi:schemaLocation`. Estas son agregadas directamente por las clases de `CfdiUtils\Elements`.

Esto te generará:

```xml
<cfdi:Comprobante
  xmlns:cfdi="http://www.sat.gob.mx/cfd/3"
  xmlns:pago10="http://www.sat.gob.mx/Pagos"
  xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <cfdi:Complemento>
    <pago10:Pagos xmlns:pago10="http://www.sat.gob.mx/Pagos"
      xsi:schemaLocation="http://www.sat.gob.mx/Pagos http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos10.xsd">
    </pago10:Pagos>
  </cfdi:Complemento>
</cfdi:Comprobante>
```

Este XML es válido pero no cumple estrictamente con la definición del Anexo 20 y de los complementos, entonces puedes hacer:

```php
// mover los namespace definitions al elemento raíz
$creator->moveSatDefinitionsToComprobante();
```

Que te dejará las definiciones tal como las pide el SAT:

```xml
<cfdi:Comprobante
  xmlns:cfdi="http://www.sat.gob.mx/cfd/3"
  xmlns:pago10="http://www.sat.gob.mx/Pagos"
  xsi:schemaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/Pagos http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos10.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <cfdi:Complemento>
    <pago10:Pagos>
    </pago10:Pagos>
  </cfdi:Complemento>
</cfdi:Comprobante>
```

Nota 1: He omitido intencionalmente la demás información, es solo para ilustrar lo de los espacios de nombres de CFDI.
Nota 2: Los campos fijos como `Version` también son incluidos automáticamente.
Nota 3: Si estás usando directamente `Nodes` en lugar de `Elements`, entonces sí tendrás que hacer las definiciones de espacios de nombres, el método `moveSatDefinitionsToComprobante` igualmente funcionará.

**Comment by eclipxe13** [comment]
@aumeli74 te sirvió la respuesta?

**Comment by aumeli74** [comment]
Hola, probe esto


$comprobanteAtributos = [
    //'xmlns:cfdi' => "http://www.sat.gob.mx/cfd/3",
    //'xmlns:xsi' => "http://www.w3.org/2001/XMLSchema-instance",
    //'xsi:schemaLocation' => "http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd http://www.sat.gob.mx/Pagos http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos10.xsd" ,
    'xmlns:pago10' =>  "http://www.sat.gob.mx/Pagos",
    'Version' => "3.3",
    'Fecha' => $fecha,
...
..
..
..
$creator->moveSatDefinitionsToComprobante();
$xml_content = $creator->asXml();

Y me produce lo mismo
 

<?xml version="1.0" encoding="UTF-8"?>
<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:sch
emaLocation="http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd" Version="3.3" xmlns:pago
10="http://www.sat.gob.mx/Pagos”


Saludos

**Comment by eclipxe13** [comment]
Me parece muy raro, no es así como debe funcionar.

Mira este ejemplo (test case) en donde se está creando un CFDI de pagos de prueba:
<https://github.com/eclipxe13/CfdiUtils/blob/master/tests/CfdiUtilsTests/CreateComprobantePagosCaseTest.php>
que produce el siguiente resultado
<https://github.com/eclipxe13/CfdiUtils/blob/master/tests/assets/created-pago-with-ns-at-root.xml>

Como puedes ver, está poniendo correctamente las declaraciones de espacios de nombres y las ubicaciones de los esquemas.

1. ¿podrías compartir el código completo de lo que estás haciendo?
2. También estamos en <https://discord.gg/aFGYXvX> donde la comunidad te podría dar soporte para resolver el problema.

**Comment by isayam** [comment]
https://github.com/eclipxe13/CfdiUtils/issues/56#issuecomment-686837766

Los links no funcionan, en algun otro lugar podria ver esos ejemplos ?

**Comment by TheSpectroMx** [comment]
Hola @isayam  este es el link correcto:

https://github.com/eclipxe13/CfdiUtils/blob/master/tests/CfdiUtilsTests/CreateComprobantePagos33CaseTest.php
