### ISSUE TITLE
Error al validar CFDI Tipo T (Traslado)

### ISSUE THREAD

**Issue by TheSpectroMx** [eclipxe13/CfdiUtils#58]
Al validar un CFDI del Tipo T (Traslado) me arroja el siguiente mensaje de error:

ERROR: FORMAPAGO01 - El campo forma de pago no debe existir cuando existe el complemento para recepción de pagos (CFDI33103)

Al abrir el XML no existe dicho complemento.

**Comment by eclipxe13** [comment]
work in progress... gracias por la detección

**Comment by eclipxe13** [comment]
Liberé la versión https://github.com/eclipxe13/CfdiUtils/releases/tag/v2.13.1 que soluciona este problema, gracias!!
