### ISSUE TITLE
xlst de validacion de cadena original, de manera local

### ISSUE THREAD

**Issue by aumeli74** [eclipxe13/CfdiUtils#68]
hola , recientemente en un proyecto , debido a restricciones de sitios y seguridad de la compañia que es excesivamente restrictiva  en el acceso a sitios, validando con la gente de seguridad ellos hablan que al descargar  el archivo para validacion y generacion de la cadena original  (cadenaoriginal_3_3.xslt )  genera un paquete de RESET en el sitio del SAT. Resultado ,si accedes al SAT pero se corta la transmision por ese RESET que hace el SAT , temas complicados y que son dificiles que entre administradores se puedan resolver.

La solucion ,descargue los archivos localmente y ajuste el archivo src/CfdiUtils/CadenaOrigen/CfdiDefaultLocations.php paraque apunta a mi host local http://localhost/xlst/cadenaoriginal_3_3.xslt junto a sus dependencias. 

Duda,  existe alguna opcion de sobreescribir esta extender esta clase y registrarla para que responda con una ruta local o alguna otra modificada ?

**Comment by eclipxe13** [comment]
`cfdiutils` se puede configurar para que:

- Todos los recursos los consuma de internet (no recomendado)
- Almacene copias locales de los recursos mientras los va necesitando (default, los guarda en `vendor/eclipxe/cfdiutils/build/resources/`)
- Tú tengas las copias locales y las almacenes en una carpeta local. (recomendado)

Para tus copias locales, puedes usar [`phpcfdi/resources`](https://github.com/phpcfdi/resources-sat-xml) y actualizar periódicamente tu conjunto de datos con un script como [`resource-sat-xml-download`](https://github.com/eclipxe13/CfdiUtils/blob/master/tests/resource-sat-xml-download).

Mira estas partes de la documentación:
- https://cfdiutils.readthedocs.io/es/latest/crear/crear-cfdi.html#resolvedor-de-recursos-xml
- https://cfdiutils.readthedocs.io/es/latest/componentes/xmlresolver.html
