### ISSUE TITLE
Complementos de pagos

### ISSUE THREAD

**Issue by EduardoCollazoR** [eclipxe13/CfdiUtils#72]
Como evito que la etiqueta pago10:Pago se repita en cada pago10:DoctoRelacionado, ya que estos  estan como hijos dentro de la etiqueta pago10:Pagos

`<pago10:Pagos xmlns:pago10="http://www.sat.gob.mx/Pagos" xsi:schemaLocation="http://www.sat.gob.mx/Pagos http://www.sat.gob.mx/sitio_internet/cfd/Pagos/Pagos10.xsd" Version="1.0">
      <pago10:Pago FechaPago="2021-10-14T17:31:34" FormaDePagoP="1" MonedaP="MXN" Monto="400"/>
      <pago10:Pago>
        <pago10:DoctoRelacionado idDocumento="F61BF8D0-11A0-45ED-9F2F-C69DEF0B426D" Serie="RRF" Folio="126" MonedaDR="MXN" MetodoDePagoDR="PPD" NumParcialidad="1" ImpSaldoAnt="383.2" ImpPagado="383.2" ImpSaldoInsoluto="0"/>
      </pago10:Pago>
      <pago10:Pago>
        <pago10:DoctoRelacionado idDocumento="19D2F772-8D33-43FB-A09E-7C827574DF42" Serie="RRF" Folio="129" MonedaDR="USD" MetodoDePagoDR="PPD" TipoCambioDR="20.44" NumParcialidad="1" ImpSaldoAnt="8.53" ImpPagado="0.82" ImpSaldoInsoluto="7.71"/>
      </pago10:Pago>
    </pago10:Pagos>`

**Comment by eclipxe13** [comment]
La etiqueta a la que te refieres es el *XML namespace prefix* y no debería omitirse, es parte de la especificación técnica de cómo se debe generar el complemento de pagos.

Si la deseas omitir (que no te lo recomiendo) se necesita reprocesar el documento. Dime si es exactamente eso lo que necesitas para orientarte en la respuesta.

**Comment by celli33** [comment]
Creo que lo que requieres hacer es algo como esto: 
`php
$complementoPagos = new Pagos();
$pagoCreated = $this->addPago($complementoPagos, $pago);
foreach ($pago->relacionados as $relacionado) {
         $this->addRelacionado($pagoCreated, $relacionado);
}
$this->comprobante->addComplemento($complementoPagos);
`
