### ISSUE TITLE
Soporte para php 8.1

### ISSUE THREAD

**Issue by miriam-mostra** [eclipxe13/CfdiUtils#90]
Al actualizar a la versión 9 de laravel, lanza un error debido a que no soporta php 8.1

**Comment by eclipxe13** [comment]
Efectivamente, por el momento no hemos solucionado la compatibilidad con PHP 8.1
Próximamente liberaré una actualización que garantice su uso.
Si tienes alguna propuesta las PR están abiertas.

**Comment by eclipxe13** [comment]
Por cierto, tengo entendido que Laravel 9 soporta PHP 8.0
https://laravel.com/docs/9.x/releases#support-policy

Aún así, el soporte de PHP 8.1 tiene que ser realizado

**Comment by eclipxe13** [comment]
Se ha creado el PR #91 para garantizar la compatibilidad e instalación con PHP 8.1

**Comment by eclipxe13** [comment]
Solucionado en la versión 2.20.1
