### ISSUE TITLE
Ejemplo de Pago20 

### ISSUE THREAD

**Issue by DanielVera987** [eclipxe13/CfdiUtils#98]
Hola buen día a quien corresponda.

Hay algún ejemplo de cómo implementar el Pago20 sobre todo el nodo de Totales.?

Muchas gracias de antemano

**Comment by TheSpectroMx** [comment]
Hola @DanielVera987 por lo general no tardamos tanto y espero te sirva aún la información, deberías de tener algo así:

```php
$complementoPagos = new Pagos();

$totales = $complementoPagos->addTotales([
    //* Atributos */
]);

$pago = $complementoPagos->addPago([
    //* Atributos */
]);

$docrelacionado = $pago->addDoctoRelacionado([
    //* Atributos */
]);

$totales = $complementoPagos->addTotales([
    //* Atributos */
]);

$comprobante->addComplemento($complementoPagos);

$creator->addSumasConceptos(null, 0);
```

En ese caso no estoy colocando la parte de ImpuestosDR de los Documentos relacionados y por lo tanto tampoco ImpuestosP. Quedamos al pendiente de tus comentarios y si puedes te invito a unirte a la comunidad en discord en https://discord.gg/aFGYXvX  ahí es más rápida la forma de interactuar.

**Comment by DanielVera987** [comment]
Muchas gracias @TheSpectroMx, si me es util la info. La función addSumasConceptos me agrega algunos campos en los Totales de Pago20?

**Comment by TheSpectroMx** [comment]
No agrega ningún atributo en el nodo Totales, en este caso `addSumasConceptos(null, 0);` lo que hace es que de cada concepto suma suma los valores de importes y descuento para poner a en el nodo comprobante los atributos `SubTotal, Descuento y Total`

**Comment by DanielVera987** [comment]
Gracias, me queda claro 🙌
